name: test
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        - stable
        - beta
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - run: cargo test
      env:
        RUSTFLAGS: "-Clink-arg=-Wl,--allow-multiple-definition"
